language: ruby
cache: bundler
rvm:
- 2.0.0
- 2.1.0
- 2.2.0
- 2.3.0
sudo: false
deploy:
  provider: rubygems
  gem:
    master: maia
  on:
    repo: lserman/maia
    branch: master
  api_key:
    secure: Odr8jOiXRDTmdU290OIZ4GNWt3YRhxJlcJy2RTTWB8IWi9xy72kyaovdjVXEavkouyGfUw319lrFqZ1QvP2GsD4r1WOY/2Wyf2PVdOqERFYEEBJQQ82P+mH1VqyxuFPKKQi1im6TQP88G3BsMPipyFEwYI3Lltbs9ovvc93U10PL3LHGYRvnSbBWNtZPTiQUOdhFQ23J3Ik4nRFtlL9s2GoGqLtjub8Z7HgH/jXAcXX+aYEHYHmVMFxEUwmAAHJfjLXxBXnTONS1uR0CBgP5MuUb9VUgvChJ+iAXX9uN9jbQnfQ+PGIuStijyVLZaEDAKEtq5ZDa6yyMkOuezjlc0hyCedFv2JDveQkkBLGalzf0mlgEV6KmBNNbbCmyqPgGr6jMJNdpsOkGEA6wai4du9IIpeNAmACvDSdGXmsito0x/bvAQvONqv20YP0uDvVaPRh+hh0C3xYYiKTBBBdDvjT9YZvrGS5ebJ5FuCMeNi7xcPhTcBgdjg+8VMUANc1WtOUjKiCYGgLtmzQh6vjNvjhXsLe9sBe+REMpQEqckkSVggC7BlmvQtUVdtxwT6pPSS9qpnVAr8OjS+Yy5sZsuEnfG5ufsaiDoh2/vv1erOtsmj8hB+Ye5cYRz87HWHClRAO+Ci50/uUtKpJif4ihRo9VEYLJ8bQrlU7e71yXvCU=
